### ISSUE TITLE
Wie CO2-Sensor kalibrieren?

### ISSUE THREAD

**Issue by ghost** [make-IoT/CO2-Ampel#2]
Hallo :)

im anderen Issue hattest du geschrieben:
> bitte wenn der Sensor am PC hängt in der Arduino IDE unter Serial Monitor schauen: da sollten die Rohwerte des CO2 Sensors erscheinen .. an frischer Luft sollten die nach ca 2 min um 410 ppm liegen, dann ist alle korrket ;-) (+/-50 ppm)

Da mir die Ampel immer zu schnell wieder rot und zu oft orange vorkam, hab ich jetzt mal die Rohwerte gemessen und da sind die Werte an der frischen Luft (nach mehr als 2 Minuten) auf jeden Fall zu hoch (zwischen 800-900 ppm).

Wie kann ich das Teil jetzt kalibrieren?

Vielen Dank und liebe Grüße
Jago

**Comment by make-IoT** [comment]
Hallo Jago,

vermutlich ja - beim Kalibrieren bitte darauf achten das es um den Sensor windstill ist und der Messwert nach einigen Minuten stabil ist, dann die Kalibrierung durchführen,
der Wert sollte dann um die 410ppm +/- 50ppm liegen

**Comment by ghost** [comment]
Hallo,
danke für deine Antwort!

Mir ging es eher um das "wie" als um das "ob" ;-)
Ich hab jetzt mit Insomnia Core (https://insomnia.rest/) den Post-Request zum Kalibrieren erstellt, weil ich auf der Page keine Möglichkeit dazu gesehen hab. Geht das auch einfacher?

Auf Windstille hab ich nicht geachtet, guter Hinweis :)
Werd ich dann vielleicht nochmal neu kalibrieren. Ist aber jetzt schon deutlich besser als vorher ;)

**Comment by make-IoT** [comment]
schau mal hier https://www.umwelt-campus.de/forschung/projekte/iot-werkstatt/ideen-zur-corona-krise-1

unter kalibrieren 

oder https://github.com/make-IoT/CO2-Ampel/blob/main/CO2-Ampel-DIY-Octopus-SCD30-WEB-AP-CAL.ino

ist eine Zeile code hier als webserver page mit password schutz gebaut aber die kalibierung ist ein Befehl in der lib
